name: holas

on: [push]

jobs:
  hola:
    runs-on: windows-latest
    steps:
      - name: hola
        run: echo "holas"
  others:
    runs-on: windows-latest
    steps:
      - name: LS
        run: tree