name: holas

on:
  push:
    branches:
      - main

jobs:
  hola:
    runs-on: windows-latest
    steps:
      - name: hola
        run: echo "holas"
  others:
    runs-on: windows-latest
    steps:
      - name: LS
        run: ls -la